In [2]:
##############################################
# Modeling
##############################################
from keras import layers, models
from sklearn import preprocessing
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl
from sklearn.model_selection import train_test_split


plt.rcParams['font.family'] = "Malgun Gothic"
mpl.rcParams['axes.unicode_minus'] = False
%matplotlib inline

#gpu sync problem
import tensorflow as tf
from keras.backend import tensorflow_backend as K
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
K.set_session(tf.Session(config=config))

Using TensorFlow backend.


In [3]:
a= [[1,2,3,],[4,5,6],[6,7,8],[9,10,11]]

In [5]:
a = np.array(a)

In [29]:
a= [[1,2,3,],[4,5,6],[6,7,8],[9,10,11]]
a = np.array(a)
print(a)
print(a.shape)

scaler = preprocessing.MinMaxScaler()
a = scaler.fit_transform(a)
print(a)
print(a.shape)


a= [[1,2,3,],[4,5,6],[6,7,8],[9,10,11]]
a = np.array(a)
a = np.moveaxis(a,[0,1],[1,0])


print(a)
scaler = preprocessing.MinMaxScaler()
a = scaler.fit_transform(a)
print(a)
print(a.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[0.    0.    0.   ]
 [0.375 0.375 0.375]
 [0.625 0.625 0.625]
 [1.    1.    1.   ]]
(4, 3)
[[ 1  4  6  9]
 [ 2  5  7 10]
 [ 3  6  8 11]]
[[0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5]
 [1.  1.  1.  1. ]]
(3, 4)


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [47]:

a= [[1,2,3,],[4,5,6],[6,7,8],[9,10,11]]
a = np.array(a)
print("a의 shape",a.shape)
mshape = a.shape
print('flatten 전의 a scaler')
a = scaler.fit_transform(a)
print(a)

a= [[1,2,3,],[4,5,6],[6,7,8],[9,10,11]]
a = np.array(a)
#a=a.flatten()
print("flatten A",a)
a= a.reshape(-1,1)
a = scaler.fit_transform(a)
a=a.reshape(mshape)
print('flatten 진행후 scaler')
print(a)

a의 shape (4, 3)
flatten 전의 a scaler
[[0.    0.    0.   ]
 [0.375 0.375 0.375]
 [0.625 0.625 0.625]
 [1.    1.    1.   ]]
flatten A [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
flatten 진행후 scaler
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.5 0.6 0.7]
 [0.8 0.9 1. ]]


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
